/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path')
const fs = require('fs')
const exec = require('child_process').exec

const indexPath = path.resolve('./dist/index.html')
const contents = fs.readFileSync(indexPath, { encoding: 'utf8' })
// Fix incorrect js path generated by parcel builder
const replaced = contents.replace(`script type="module" src="/`, `script type="module" src="./`)
fs.writeFileSync(indexPath, replaced)
exec('gh-pages -d dist')
